import translations from "../i18n/en.json" with { type: "json" };
// Every public control is described here; UI, exports and documentation share this schema.
export const parameterSchema = [
  {
    key: "radius",
    label: "主环半径",
    group: "几何",
    default: 0.46,
    min: 0.25,
    max: 0.7,
    step: 0.005,
    unit: "H/2",
    evidence: "拟合 · L10",
    description:
      "以画布半高为 1；0.46 为参考尺度，实际半径随各时点拟合轮廓变化。",
  },
  {
    key: "lineWidth",
    label: "亮芯线宽",
    group: "几何",
    default: 0.006,
    min: 0.002,
    max: 0.022,
    step: 0.001,
    unit: "H/2",
    evidence: "拟合 · L10",
    description:
      "高斯亮芯的半宽，决定细白光线的锐度；700 px 高时默认约 2.1 px。",
  },
  {
    key: "wobble",
    label: "轮廓起伏",
    group: "几何",
    default: 0.012,
    min: 0,
    max: 0.05,
    step: 0.001,
    unit: "H/2",
    evidence: "拟合 · L10 0–3s",
    description: "主环低频形变振幅，0 为完美圆。",
  },
  {
    key: "echoOffset",
    label: "拖影偏移",
    group: "几何",
    default: 0.036,
    min: 0,
    max: 0.1,
    step: 0.002,
    unit: "H/2",
    evidence: "拟合 · L10 0–3s",
    description: "偏心光带相对主环的位移，保留原片的非对称尾迹。",
  },
  {
    key: "gyroTilt",
    label: "旋转环倾角",
    group: "几何",
    default: 1.06,
    min: 0,
    max: 1.42,
    step: 0.01,
    unit: "rad",
    evidence: "拟合 · L10 14–16s",
    description: "投影到屏幕的倾角；cos(倾角) 控制椭圆短轴，约 60.7°。",
  },
  {
    key: "bloomWidth",
    label: "近场泛光宽度",
    group: "光感",
    default: 0.025,
    min: 0.005,
    max: 0.09,
    step: 0.002,
    unit: "H/2",
    evidence: "拟合 · L10",
    description: "亮芯外侧的柔和辉光半宽；独立于线宽。",
  },
  {
    key: "haloWidth",
    label: "远场光晕宽度",
    group: "光感",
    default: 0.105,
    min: 0.03,
    max: 0.28,
    step: 0.005,
    unit: "H/2",
    evidence: "拟合 · L10",
    description: "更低频的大范围彩色散射，让亮线融入底色。",
  },
  {
    key: "intensity",
    label: "主环亮度",
    group: "光感",
    default: 1.35,
    min: 0.3,
    max: 3,
    step: 0.05,
    unit: "×",
    evidence: "拟合 · L10",
    description: "亮芯增益，过高会使彩色区域趋近白色。",
  },
  {
    key: "bloom",
    label: "近场泛光强度",
    group: "光感",
    default: 0.72,
    min: 0,
    max: 1.6,
    step: 0.02,
    unit: "×",
    evidence: "拟合 · L10",
    description: "彩色高斯泛光的叠加强度。",
  },
  {
    key: "halo",
    label: "远场光晕强度",
    group: "光感",
    default: 0.3,
    min: 0,
    max: 0.9,
    step: 0.01,
    unit: "×",
    evidence: "拟合 · L10",
    description: "大范围散射的强度。",
  },
  {
    key: "coreDepth",
    label: "球心色深",
    group: "光感",
    default: 0.68,
    min: 0,
    max: 1,
    step: 0.01,
    unit: "×",
    evidence: "拟合 · L10",
    description: "球心蓝紫色对背景的覆盖程度，0 时接近空心。",
  },
  {
    key: "echoOpacity",
    label: "拖影强度",
    group: "光感",
    default: 0.34,
    min: 0,
    max: 0.8,
    step: 0.01,
    unit: "α",
    evidence: "拟合 · L10 0–3s",
    description: "主环附近偏心光带的可见度。",
  },
  {
    key: "rippleOpacity",
    label: "扩散环强度",
    group: "光感",
    default: 0.18,
    min: 0,
    max: 0.6,
    step: 0.01,
    unit: "α",
    evidence: "拟合 · L10 4–13s",
    description: "同心外环发光程度，保持次于主环。",
  },
  {
    key: "rippleCount",
    label: "扩散环数量",
    group: "节奏",
    default: 3,
    min: 1,
    max: 5,
    step: 1,
    unit: "层",
    evidence: "观察/拟合 · L10",
    description: "扩散阶段同时参与计算的同心环数量；默认 3 层。",
  },
  {
    key: "ripplePeriod",
    label: "扩散周期",
    group: "节奏",
    default: 3.1,
    min: 1,
    max: 6,
    step: 0.1,
    unit: "s",
    evidence: "拟合 · L10 4–13s",
    description: "一圈从起始半径运动到最外缘所需时间。",
  },
  {
    key: "rippleTravel",
    label: "扩散距离",
    group: "节奏",
    default: 0.39,
    min: 0.1,
    max: 0.65,
    step: 0.01,
    unit: "H/2",
    evidence: "拟合 · L10",
    description: "外环在一个周期内向外移动的径向距离。",
  },
  {
    key: "colorSpeed",
    label: "色带角速度",
    group: "节奏",
    default: 0.72,
    min: -2,
    max: 2,
    step: 0.02,
    unit: "rad/s",
    evidence: "拟合 · L10",
    description: "颜色沿主环的流动速度；负值反向，不影响几何旋转。",
  },
  {
    key: "gyroSpeed",
    label: "环面角速度",
    group: "节奏",
    default: 2.25,
    min: 0.2,
    max: 5,
    step: 0.05,
    unit: "rad/s",
    evidence: "拟合 · L10 14–16s",
    description: "交错旋转阶段的几何运动速度。",
  },
  {
    key: "breathPeriod",
    label: "呼吸周期",
    group: "节奏",
    default: 3.4,
    min: 1,
    max: 8,
    step: 0.1,
    unit: "s",
    evidence: "拟合 · L10",
    description: "微弱半径呼吸的一个完整周期。",
  },
  {
    key: "breathAmount",
    label: "呼吸幅度",
    group: "节奏",
    default: 0.012,
    min: 0,
    max: 0.07,
    step: 0.001,
    unit: "×radius",
    evidence: "拟合 · L10",
    description: "相对主环半径的呼吸幅度。",
  },
  {
    key: "cyan",
    label: "青色光",
    group: "色彩",
    default: "#54f7ef",
    type: "color",
    unit: "sRGB",
    evidence: "观感拟合 · L10",
    description: "主环青色段和冷色散射。",
  },
  {
    key: "pink",
    label: "粉色光",
    group: "色彩",
    default: "#ffaadf",
    type: "color",
    unit: "sRGB",
    evidence: "观感拟合 · L10",
    description: "主环粉色段与拖影暖色。",
  },
  {
    key: "warm",
    label: "暖白高光",
    group: "色彩",
    default: "#fff1d4",
    type: "color",
    unit: "sRGB",
    evidence: "观感拟合 · L10",
    description: "主环最亮部分的暖白色。",
  },
  {
    key: "coreColor",
    label: "球心蓝",
    group: "色彩",
    default: "#678ddd",
    type: "color",
    unit: "sRGB",
    evidence: "观感拟合 · L10",
    description: "球心基础色，通过 coreDepth 混合。",
  },
  {
    key: "auraColor",
    label: "环境紫",
    group: "色彩",
    default: "#9184e6",
    type: "color",
    unit: "sRGB",
    evidence: "观感拟合 · L10",
    description: "主环外侧低频紫色光场。",
  },
  {
    key: "speed",
    label: "播放倍率",
    group: "播放",
    default: 1,
    min: 0.1,
    max: 2,
    step: 0.1,
    unit: "×",
    evidence: "复刻工具",
    description: "整个 23.217 s 参考时间轴的速率，1 为原速。",
  },
  {
    key: "pixelRatio",
    label: "渲染像素比",
    group: "画质",
    default: 1.5,
    min: 1,
    max: 2,
    step: 0.25,
    unit: "DPR",
    evidence: "实现参数",
    description: "Canvas 像素密度上限；较大数值更锐利但增加 GPU 工作量。",
  },
  {
    key: "maxFps",
    label: "帧率上限",
    group: "画质",
    default: 60,
    min: 15,
    max: 60,
    step: 15,
    unit: "fps",
    evidence: "实现参数",
    description: "限制重绘频率；暂停、不可见或减少动态效果时按需绘制。",
  },
];
export const defaults = Object.fromEntries(
  parameterSchema.map((p) => [p.key, p.default]),
);
export const referenceDuration = 23.217;
export function sanitizeParameters(input = {}) {
  const out = { ...defaults };
  for (const p of parameterSchema) {
    const value = input[p.key];
    if (p.type === "color") {
      if (typeof value === "string" && /^#[0-9a-f]{6}$/i.test(value))
        out[p.key] = value;
    } else if (typeof value === "number" && Number.isFinite(value)) {
      out[p.key] = Math.min(p.max, Math.max(p.min, value));
      if (p.step === 1 || p.key === "maxFps")
        out[p.key] = Math.round(out[p.key] / p.step) * p.step;
    }
  }
  return out;
}
export function parameterExport(values) {
  return {
    version: "2.2",
    engine: "Three.js TSL",
    duration: referenceDuration,
    parameters: sanitizeParameters(values),
    schema: parameterSchema.map((p) => ({
      ...p,
      labelEn: translations[p.label],
      groupEn: translations[p.group],
      descriptionEn: translations[p.description],
      evidenceEn: translations[p.evidence],
    })),
    evidence:
      "Colors and geometry are reconstructed from L10. Not the proprietary source shader.",
  };
}
