// CSS pixels at a 360px-wide specimen; numerical values are reconstruction estimates.
export const v7ParameterSchema = [
  {
    key: "lineWidth",
    label: "亮线宽度",
    labelEn: "Core width",
    default: 1,
    min: 0.25,
    max: 5,
    step: 0.25,
    unit: "CSS px",
    description: "边缘与轮廓的亮核半宽。",
    descriptionEn: "Half-width of the edge and contour core.",
    evidence: "L19 12s / 106s; estimate",
  },
  {
    key: "innerWidth",
    label: "内侧扩散",
    labelEn: "Inner diffusion",
    default: 4,
    min: 1,
    max: 30,
    step: 0.5,
    unit: "CSS px",
    description: "轮廓向内的柔光半宽。",
    descriptionEn: "Inner contour diffusion half-width.",
    evidence: "L19 106s; estimate",
  },
  {
    key: "outerWidth",
    label: "外侧扩散",
    labelEn: "Outer diffusion",
    default: 9,
    min: 1,
    max: 40,
    step: 0.5,
    unit: "CSS px",
    description: "轮廓向外的柔光半宽。",
    descriptionEn: "Outer contour diffusion half-width.",
    evidence: "L19 106s; estimate",
  },
  {
    key: "intensity",
    label: "光效强度",
    labelEn: "Intensity",
    default: 0.85,
    min: 0,
    max: 1,
    step: 0.01,
    unit: "alpha",
    description: "叠加层最高透明度。",
    descriptionEn: "Maximum overlay opacity.",
    evidence: "L19 8s / 12s; estimate",
  },
  {
    key: "spread",
    label: "光场范围",
    labelEn: "Field spread",
    default: 0.3,
    min: 0.1,
    max: 0.6,
    step: 0.01,
    unit: "height ratio",
    description: "底部光场向上的覆盖比例。",
    descriptionEn: "Vertical extent of the bottom light field.",
    evidence: "L19 8s; estimate",
  },
  {
    key: "speed",
    label: "流动速度",
    labelEn: "Flow speed",
    default: 0.35,
    min: 0,
    max: 2,
    step: 0.05,
    unit: "rad/s",
    description: "色带移动速度；小球运动未实测。",
    descriptionEn: "Color-band speed; orb movement is not measured.",
    evidence: "L19; fitted animation, not original timing",
  },
  {
    key: "radius",
    label: "表面圆角",
    labelEn: "Surface radius",
    default: 30,
    min: 8,
    max: 48,
    step: 1,
    unit: "CSS px",
    description: "浮卡轮廓圆角。",
    descriptionEn: "Floating surface corner radius.",
    evidence: "L19 12s; 60 source px estimate",
  },
  {
    key: "enterMs",
    label: "出现时长",
    labelEn: "Entrance duration",
    default: 360,
    min: 0,
    max: 1200,
    step: 20,
    unit: "ms",
    description: "透明度进入的复刻时长。",
    descriptionEn: "Reconstructed opacity entrance duration.",
    evidence: "L19 6–12s; estimate",
  },
  {
    key: "exitMs",
    label: "消退时长",
    labelEn: "Exit duration",
    default: 240,
    min: 0,
    max: 1000,
    step: 20,
    unit: "ms",
    description: "透明度消退的复刻时长。",
    descriptionEn: "Reconstructed opacity exit duration.",
    evidence: "L19 168–171s; estimate",
  },
  {
    key: "blue",
    label: "冷色光",
    labelEn: "Cool light",
    default: "#78b8ff",
    type: "color",
    unit: "sRGB hex",
    description: "蓝色环境光。",
    descriptionEn: "Blue ambient light.",
    evidence: "L19 8s; visual fit",
  },
  {
    key: "pink",
    label: "暖色光",
    labelEn: "Warm light",
    default: "#ffc0b4",
    type: "color",
    unit: "sRGB hex",
    description: "粉橙环境光。",
    descriptionEn: "Peach-pink ambient light.",
    evidence: "L19 8s; visual fit",
  },
  {
    key: "violet",
    label: "轮廓紫",
    labelEn: "Contour violet",
    default: "#d5b3ff",
    type: "color",
    unit: "sRGB hex",
    description: "圈选与帮写的紫色调。",
    descriptionEn: "Violet tone for selection and writing.",
    evidence: "L19 106s / 273s; visual fit",
  },
];
export const v7Defaults = Object.fromEntries(
  v7ParameterSchema.map((p) => [p.key, p.default]),
);
export function sanitizeV7Parameters(values = {}) {
  return Object.fromEntries(
    v7ParameterSchema.map((p) => [
      p.key,
      p.type === "color"
        ? /^#[\da-f]{6}$/i.test(values[p.key])
          ? values[p.key]
          : p.default
        : Number.isFinite(values[p.key])
          ? Math.min(p.max, Math.max(p.min, values[p.key]))
          : p.default,
    ]),
  );
}
export const shoeContour = [
  [24, 84],
  [30, 60],
  [51, 56],
  [60, 22],
  [88, 34],
  [110, 53],
  [144, 59],
  [173, 80],
  [177, 96],
  [161, 109],
  [41, 109],
  [25, 100],
].map(([x, y]) => [((x - 100) * 0.7) / 170, ((y - 60) * 0.7) / 205]);
